In [114]:
%matplotlib inline
import numpy as np
import pandas as pd
pd.options.display.max_rows = 10

In [115]:
import json
import requests

bptf_key = "58324a43c440450c7d4e2679"

resp = requests.get("https://backpack.tf/api/IGetPrices/v4?key=" + bptf_key)
json_result = resp.json()

In [116]:
hat_data_df = pd.read_csv("Full Hat Data.csv")
hat_data_df =hat_data_df[hat_data_df.columns.drop("Unnamed: 0")]

In [117]:
from __future__ import print_function
import pickle
import os.path
from googleapiclient.discovery import build
from google_auth_oauthlib.flow import InstalledAppFlow
from google.auth.transport.requests import Request

# If modifying these scopes, delete the file token.pickle.
SCOPES = ['https://www.googleapis.com/auth/spreadsheets.readonly']

# The ID and range of a sample spreadsheet.
SAMPLE_SPREADSHEET_ID = '1e6T2zlrZ1kaXXX-4b75b7vrwH51kh4SReAia2A0OFn8'
SAMPLE_RANGE_NAME = 'B1:DO'

creds = None
# The file token.pickle stores the user's access and refresh tokens, and is
# created automatically when the authorization flow completes for the first
# time.
if os.path.exists('token.pickle'):
    with open('token.pickle', 'rb') as token:
        creds = pickle.load(token)
# If there are no (valid) credentials available, let the user log in.
if not creds or not creds.valid:
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    else:
        flow = InstalledAppFlow.from_client_secrets_file(
            'credentials.json', SCOPES)
        creds = flow.run_local_server()
    # Save the credentials for the next run
    with open('token.pickle', 'wb') as token:
        pickle.dump(creds, token)

service = build('sheets', 'v4', credentials=creds)

# Call the Sheets API
sheet = service.spreadsheets()
result = sheet.values().get(spreadsheetId=SAMPLE_SPREADSHEET_ID,
                                range=SAMPLE_RANGE_NAME).execute()
ratings_df = pd.DataFrame(result["values"])

In [118]:
ratings_df = ratings_df.rename(columns=ratings_df.iloc[0]).drop([0])
ratings_df_s = ratings_df.T

In [119]:
ratings_df_s[ratings_df_s.columns] = ratings_df_s[ratings_df_s.columns].apply(pd.to_numeric)
mean_values = ratings_df_s.mean(axis = 1).sort_values(ascending = False)
community_rating_df = pd.DataFrame(mean_values).reset_index().rename(columns = {"index" : "Effect", 0: "Effect Community Rating"})
print(community_rating_df.to_string())

                               Effect  Effect Community Rating
0                              Nebula                 4.875000
1                    Scorching Flames                 4.625000
2                      Burning Flames                 4.593750
3                           Frostbite                 4.437500
4                    Galactic Gateway                 4.406250
5                    The Dark Doorway                 4.312500
6                            Sunbeams                 4.312500
7                          Spellbound                 4.312500
8                The Eldritch Opening                 4.281250
9                       Death at Dusk                 4.281250
10              Bonzo The All-Gnawing                 4.250000
11                      Purple Energy                 4.218750
12                   Stormy 13th Hour                 4.218750
13                             Arcana                 4.187500
14         It's A Secret To Everybody                 4.187500
15                       Green Energy                 4.156250
16                      Morning Glory                 4.156250
17                        Cloudy Moon                 4.125000
18                         Knifestorm                 4.093750
19                           Hellfire                 4.062500
20                       Harvest Moon                 4.000000
21                          Time Warp                 4.000000
22                          Darkblaze                 4.000000
23                         Demonflame                 3.968750
24                        Misty Skull                 3.906250
25                   Poisoned Shadows                 3.875000
26                   Green Black Hole                 3.812500
27   Something Burning This Way Comes                 3.687500
28                Chiroptera Venenata                 3.656250
29                         Roboactive                 3.612903
30                    Disco Beat Down                 3.531250
31                           The Ooze                 3.468750
32                        Amaranthine                 3.468750
33                        Anti-Freeze                 3.406250
34                  Stare From Beyond                 3.406250
35                      Ominous Night                 3.218750
36                    Infernal Flames                 3.156250
37                    Blizzardy Storm                 3.156250
38                       Nether Trail                 3.125000
39                     Death by Disco                 3.093750
40                       Spooky Night                 3.062500
41                     Circling Heart                 3.062500
42                     Infernal Smoke                 3.062500
43                     Haunted Ghosts                 3.031250
44                        Ether Trail                 3.031250
45                   Haunted Phantasm                 2.968750
46                          Abduction                 2.937500
47                         Holy Grail                 2.906250
48                       Miami Nights                 2.906250
49                     Ghastly Ghosts                 2.906250
50                       Vivid Plasma                 2.875000
51                    Hellish Inferno                 2.875000
52                     Spectral Swirl                 2.875000
53                         Tesla Coil                 2.875000
54                   Ancient Eldritch                 2.875000
55                       Stormy Storm                 2.812500
56                  Ghastly Ghosts Jr                 2.812500
57                     Eldritch Flame                 2.781250
58                Haunted Phantasm Jr                 2.750000
59         It's a mystery to everyone                 2.750000
60                    White Lightning                 2.718750
61                     Searing Plasma                 2.687500
62                It's a puzzle to me                 2.656250
63                            Cloud 9                 2.625000
64                       Ring of Fire                 2.593750
65                Fountain of Delight                 2.531250
66                         Sulphurous                 2.531250
67                       Clairvoyance                 2.531250
68                  Starstorm Slumber                 2.500000
69                        Phosphorous                 2.468750
70                    Screaming Tiger                 2.437500
71                 Starstorm Insomnia                 2.437500
72                     Vicious Circle                 2.406250
73                     Molten Mallard                 2.375000
74                   Circling TF Logo                 2.343750
75                             Atomic                 2.312500
76                          Subatomic                 2.281250
77                       Neutron Star                 2.250000
78                Circling Peace Sign                 2.218750
79                        Showstopper                 2.218750
80                      Head of Steam                 2.187500
81                     Omniscient Orb                 2.156250
82             Electric Hat Protector                 2.156250
83             Magnetic Hat Protector                 2.156250
84                        Kill-a-Watt                 2.156250
85                        Terror-Watt                 2.125000
86              Voltaic Hat Protector                 2.093750
87                          Open Mind                 2.062500
88                            Smoking                 2.000000
89                        Power Surge                 1.968750
90                        Brain Drain                 1.937500
91                    Flaming Lantern                 1.937500
92                           Steaming                 1.906250
93        Poisonous Bubbles of Regret                 1.875000
94    Flammable Bubbles of Attraction                 1.875000
95                      Electrostatic                 1.875000
96                                '72                 1.875000
97                    Roaring Rockets                 1.812500
98             Acidic Bubbles of Envy                 1.781250
99                Eerie Orbiting Fire                 1.687500
100                     Orbiting Fire                 1.625000
101                  Cauldron Bubbles                 1.593750
102                         Aces High                 1.468750
103                     Ancient Codex                 1.468750
104                    Galactic Codex                 1.437500
105                          Bubbling                 1.437500
106                    Green Confetti                 1.406250
107                   Purple Confetti                 1.343750
108                       Mega Strike                 1.218750
109                   Dead Presidents                 1.125000
110                       Overclocked                 1.093750
111                  Orbiting Planets                 1.093750
112                       Memory Leak                 1.031250
113                Skill Gotten Gains                 0.843750
114                    Silver Cyclone                 0.718750
115                Midnight Whirlwind                 0.468750
116                     Nuts n' Bolts                 0.437500
117                      Massed Flies                 0.187500

In [120]:
effect_data_df = pd.read_csv("Full Effect Data.csv")
effect_data_df = effect_data_df[effect_data_df.columns.drop("Unnamed: 0")]
effect_data_df = effect_data_df.merge(community_rating_df,on="Effect",how = "left")
effect_data_df

                     Effect Generation  Id  Effect Community Rating
0            Burning Flames  First Gen  13                  4.59375
1            Circling Heart  First Gen  19                  3.06250
2       Circling Peace Sign  First Gen  18                  2.21875
3          Circling TF Logo  First Gen  11                  2.34375
4            Green Confetti  First Gen   6                  1.40625
..                      ...        ...  ..                      ...
117  Magnetic Hat Protector   Invasion  95                  2.15625
118   Voltaic Hat Protector   Invasion  96                  2.09375
119          Galactic Codex   Invasion  97                  1.43750
120           Ancient Codex   Invasion  98                  1.46875
121                  Nebula   Invasion  99                  4.87500

[122 rows x 4 columns]

In [121]:
taunt_effects = effect_data_df[effect_data_df["Id"] >= 3000]
taunt_effects

                 Effect      Generation    Id  Effect Community Rating
52       Ghastly Ghosts  Halloween 2014  3012                  2.90625
53     Haunted Phantasm  Halloween 2014  3011                  2.96875
65       Spectral Swirl  Halloween 2016  3014                  2.87500
66      Hellish Inferno  Halloween 2016  3013                  2.87500
67       Infernal Smoke  Halloween 2016  3016                  3.06250
..                  ...             ...   ...                      ...
100  Midnight Whirlwind      Love & War  3008                  0.46875
101     Screaming Tiger      Love & War  3006                  2.43750
102         Showstopper      Love & War  3001                  2.21875
103      Silver Cyclone      Love & War  3009                  0.71875
104  Skill Gotten Gains      Love & War  3007                  0.84375

[21 rows x 4 columns]

In [122]:
hat_effects = effect_data_df[effect_data_df["Id"] < 200]
hat_effects

                     Effect Generation  Id  Effect Community Rating
0            Burning Flames  First Gen  13                  4.59375
1            Circling Heart  First Gen  19                  3.06250
2       Circling Peace Sign  First Gen  18                  2.21875
3          Circling TF Logo  First Gen  11                  2.34375
4            Green Confetti  First Gen   6                  1.40625
..                      ...        ...  ..                      ...
117  Magnetic Hat Protector   Invasion  95                  2.15625
118   Voltaic Hat Protector   Invasion  96                  2.09375
119          Galactic Codex   Invasion  97                  1.43750
120           Ancient Codex   Invasion  98                  1.46875
121                  Nebula   Invasion  99                  4.87500

[97 rows x 4 columns]

In [123]:
items_dict = json_result["response"]["items"]

unusual_items = np.array(hat_data_df[["Name","Item Type"]])
h_effects = np.array(hat_effects[["Effect","Id"]])
t_effects = np.array(taunt_effects[["Effect","Id"]])

final_array = []

for item in items_dict:
    
    for i in range(0,len(unusual_items)):
        
        item_to_compare = item
        if item.startswith("Taunt: "):
            item_to_compare = item[7:]
        
        if item_to_compare == unusual_items[i][0]:
        
            item_type = unusual_items[i][1]
            #print(item,item_type)
            
            item_json = items_dict[item]["prices"].get("5")["Tradable"]["Craftable"]
            
            if item_type == "Cosmetic":
                for pair in h_effects:
                    
                    effect_name = pair[0]
                    effect_id = pair[1]
                    price_final = np.nan
                    last_update = np.nan
                    
                    prices_dict = item_json.get(str(effect_id))
                    
                    if prices_dict != None:
                        
                        if prices_dict["last_update"] > 1427893200: # a price newer than April 1, 2015
                            last_update = prices_dict["last_update"]
                            
                        
                            if len(prices_dict) == 5:

                                price_low = prices_dict["value"]
                                price_high = prices_dict["value_high"]

                                price_final = float(price_low + price_high)/2

                            else:

                                price_final = prices_dict["value"]

                        
                    to_add = [item_to_compare,effect_name,price_final,last_update]
                    final_array.append(to_add)
                    
            elif item_type == "Taunt":
                for pair in t_effects:
                    
                    effect_name = pair[0]
                    effect_id = pair[1]
                    price_final = np.nan
                    last_update = np.nan
                    
                    prices_dict = item_json.get(str(effect_id))
                    
                    if prices_dict != None:
                        
                        if prices_dict["last_update"] > 1427893200: # a price newer than April 1, 2015
                            last_update = prices_dict["last_update"]
                        
                            if len(prices_dict) == 5:

                                price_low = prices_dict["value"]
                                price_high = prices_dict["value_high"]

                                price_final = float(price_low + price_high)/2

                            else:

                                price_final = prices_dict["value"]
                    
                    to_add = [item_to_compare,effect_name,price_final,last_update]
                    final_array.append(to_add)
                    
prices_df = pd.DataFrame(final_array).rename(columns = {0:"Name",1:"Effect",2:"Price",3:"Last Price Update"})
prices_df

             Name                  Effect  Price  Last Price Update
0      Dread Knot          Burning Flames   30.0       1.530629e+09
1      Dread Knot          Circling Heart    NaN                NaN
2      Dread Knot     Circling Peace Sign   10.0       1.499052e+09
3      Dread Knot        Circling TF Logo    9.0       1.439780e+09
4      Dread Knot          Green Confetti    9.0       1.514740e+09
...           ...                     ...    ...                ...
41373  Snowcapped  Magnetic Hat Protector    NaN                NaN
41374  Snowcapped   Voltaic Hat Protector    NaN                NaN
41375  Snowcapped          Galactic Codex    NaN                NaN
41376  Snowcapped           Ancient Codex    NaN                NaN
41377  Snowcapped                  Nebula    NaN                NaN

[41378 rows x 4 columns]

In [124]:
temp_df = prices_df.merge(hat_data_df,on = "Name", how = "left")

In [125]:
unusuals_df = temp_df.merge(effect_data_df,on = "Effect", how = "left")

In [126]:
import time
import calendar
unusuals_df["Crate Cosmetic"] = unusuals_df.apply(
    lambda row: True if row["Grade"] == "No Grade" and row["Item Type"] == "Cosmetic" else False,
    axis=1
) #(2019 - time.gmtime(row["Last Price Update"])[0]) * 12 + 
unusuals_df["Months Since Last Price Update"] = unusuals_df.apply(
    lambda row: -1 if pd.isnull(row["Last Price Update"]) else (time.gmtime(calendar.timegm(time.gmtime()) - row["Last Price Update"])[1] + 
    (time.gmtime(calendar.timegm(time.gmtime()) - row["Last Price Update"])[0] - 1970) * 12),
    axis=1
)

In [127]:
unusuals_df = unusuals_df[unusuals_df.columns.drop(["Id","Last Price Update"])]

In [128]:
median_effect_prices = pd.DataFrame(unusuals_df.groupby("Effect")["Price"].median().sort_values(ascending = False)).reset_index().rename(columns = {"Price" : "Effect Median Price"})
median_effect_prices

                    Effect  Effect Median Price
0                   Nebula              180.000
1                Abduction              153.750
2               Spellbound              140.000
3    Bonzo The All-Gnawing              138.500
4                   Arcana              120.000
..                     ...                  ...
113            Mega Strike                7.375
114     Skill Gotten Gains                7.250
115                    '72                7.000
116     Midnight Whirlwind                6.250
117         Silver Cyclone                5.750

[118 rows x 2 columns]

In [129]:
median_hat_prices = pd.DataFrame(unusuals_df.groupby("Name")["Price"].median().sort_values(ascending = False)).reset_index().rename(columns = {"Price" : "Hat Median Price"})
median_hat_prices

                       Name  Hat Median Price
0                Coffin Kit           2210.00
1    Coldfront Curbstompers           1750.00
2     Sleeveless in Siberia            892.00
3         Potassium Bonnett            645.00
4                   Antlers            482.50
..                      ...               ...
449          Results Are In              6.25
450      Spent Well Spirits              6.00
451      Battin' a Thousand              5.50
452               I See You              5.00
453            Hunter Heavy               NaN

[454 rows x 2 columns]

In [130]:
unusuals_df = unusuals_df.merge(median_effect_prices,on= "Effect",how = "left")
unusuals_df = unusuals_df.merge(median_hat_prices, on = "Name",how = "left")
unusuals_df

,Name,Effect,Price,Class,Item Type,Equip Region,Grade,Unboxed From,Robo,Generation,Effect Community Rating,Crate Cosmetic,Months Since Last Price Update,Effect Median Price,Hat Median Price
0,Dread Knot,Burning Flames,30.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,4.59375,True,9,104.00,14.0
1,Dread Knot,Circling Heart,NaN,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,3.06250,True,-1,36.25,14.0
2,Dread Knot,Circling Peace Sign,10.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,2.21875,True,21,22.00,14.0
3,Dread Knot,Circling TF Logo,9.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,2.34375,True,44,21.50,14.0
4,Dread Knot,Green Confetti,9.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,1.40625,True,15,17.00,14.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41373,Snowcapped,Magnetic Hat Protector,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,2.15625,False,-1,20.50,22.0
41374,Snowcapped,Voltaic Hat Protector,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,2.09375,False,-1,52.50,22.0
41375,Snowcapped,Galactic Codex,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,1.43750,False,-1,36.75,22.0
41376,Snowcapped,Ancient Codex,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,1.46875,False,-1,19.50,22.0
41377,Snowcapped,Nebula,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,4.87500,False,-1,180.00,22.0

In [137]:
unusuals_df["Hat Rating"] = (unusuals_df["Price"] - unusuals_df["Effect Median Price"]) / 10
median_hat_ratings = pd.DataFrame(unusuals_df.groupby("Name")["Hat Rating"].median().sort_values(ascending = False)).reset_index().rename(columns = {"Hat Rating" : "Median Hat Rating"})
median_hat_ratings

                       Name  Median Hat Rating
0                Coffin Kit            217.800
1    Coldfront Curbstompers            170.000
2     Sleeveless in Siberia             84.950
3         Potassium Bonnett             62.675
4                   Antlers             45.600
..                      ...                ...
449   Magnificent Mongolian             -1.900
450          Commando Elite             -2.050
451                Tank Top             -2.400
452           Cool Capuchon             -2.450
453            Hunter Heavy                NaN

[454 rows x 2 columns]

In [132]:
unusuals_df["Effect Rating"] = (unusuals_df["Price"] - unusuals_df["Hat Median Price"]) / 10
median_effect_ratings = pd.DataFrame(unusuals_df.groupby("Effect")["Effect Rating"].median().sort_values(ascending = False)).reset_index().rename(columns = {"Effect Rating" : "Median Effect Rating"})
median_effect_ratings

                    Effect  Median Effect Rating
0                   Nebula               14.5000
1               Spellbound               10.7500
2    Bonzo The All-Gnawing               10.1500
3                   Arcana                8.5000
4     The Eldritch Opening                8.0125
..                     ...                   ...
113               Bubbling               -1.7000
114           Massed Flies               -1.7000
115              Aces High               -1.7000
116       Orbiting Planets               -1.7500
117          Nuts n' Bolts               -1.8500

[118 rows x 2 columns]

In [133]:
unusuals_df = unusuals_df.merge(median_effect_ratings,on= "Effect",how = "left")
unusuals_df = unusuals_df.merge(median_hat_ratings, on = "Name",how = "left")
unusuals_df

,Name,Effect,Price,Class,Item Type,Equip Region,Grade,Unboxed From,Robo,Generation,Effect Community Rating,Crate Cosmetic,Months Since Last Price Update,Effect Median Price,Hat Median Price,Hat Rating,Effect Rating,Median Effect Rating,Median Hat Rating
0,Dread Knot,Burning Flames,30.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,4.59375,True,9,104.00,14.0,-7.40,1.6,6.7375,-1.6000
1,Dread Knot,Circling Heart,NaN,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,3.06250,True,-1,36.25,14.0,NaN,NaN,0.4500,-1.6000
2,Dread Knot,Circling Peace Sign,10.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,2.21875,True,21,22.00,14.0,-1.20,-0.4,-0.8500,-1.6000
3,Dread Knot,Circling TF Logo,9.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,2.34375,True,44,21.50,14.0,-1.25,-0.5,-0.9125,-1.6000
4,Dread Knot,Green Confetti,9.0,Heavy,Cosmetic,Regular,No Grade,Old Series,False,First Gen,1.40625,True,15,17.00,14.0,-0.80,-0.5,-1.3750,-1.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41373,Snowcapped,Magnetic Hat Protector,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,2.15625,False,-1,20.50,22.0,NaN,NaN,-0.9000,-0.1625
41374,Snowcapped,Voltaic Hat Protector,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,2.09375,False,-1,52.50,22.0,NaN,NaN,-1.1750,-0.1625
41375,Snowcapped,Galactic Codex,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,1.43750,False,-1,36.75,22.0,NaN,NaN,-1.1000,-0.1625
41376,Snowcapped,Ancient Codex,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,1.46875,False,-1,19.50,22.0,NaN,NaN,-1.2500,-0.1625
41377,Snowcapped,Nebula,NaN,Medic,Cosmetic,Regular,Mercenary,Winter 2018 Cosmetic,False,Invasion,4.87500,False,-1,180.00,22.0,NaN,NaN,14.5000,-0.1625

In [138]:
unusuals_df = unusuals_df[~unusuals_df["Median Hat Rating"].isnull()]

In [139]:
unusuals_train_df = unusuals_df[~unusuals_df["Price"].isnull()]
unusuals_predict_df = unusuals_df[unusuals_df["Price"].isnull()]

In [140]:
unusuals_df.to_csv("CompleteHatAndPricingData.csv")